### ISSUE TITLE
Designing HOMO-OLIGOMER error

### ISSUE THREAD

**Issue by Lyang556** [dauparas/LigandMPNN#10]
@dauparas Thanks for you hard work. I think I found a bug. My command is:

`python run.py \`
--fixed_residues "A51 A52 A53 B154 B155 B156 C257 C258 C259 D360 D361 D362 E463 E464 E465 F566 F567 F568" \`
--pdb_path "./design_4.pdb" \`
--out_folder "./outputs/test" \`
--batch_size 3 \`
--number_of_batches 5 \`
--temperature 0.1 \`
--homo_oligomer 1`

The error is:
 `Designing HOMO-OLIGOMER`
`Traceback (most recent call last):`
`  File "DL_biosoft/LigandMPNN/run.py", line 794, in <module>`
`    main(args)`
`  File "DL_biosoft/LigandMPNN/run.py", line 315, in main`
`    tmp_list.append(encoded_residue_dict[name])`
`                    ~~~~~~~~~~~~~~~~~~~~^^^^^^`
`KeyError: 'A310'`
`
Could you please help me solve this error? The PDB file is attached。
[design_4.zip](https://github.com/dauparas/LigandMPNN/files/14588582/design_4.zip)

Thank you.

**Comment by Lyang556** [comment]
I've solved this issue by renumbering the PDB files using the "pdb_renumber.py" script in rosetta. 
Could you please tell me if there are any other possible ways to solve this issue?
Thanks you.
