### ISSUE TITLE
index 0 is out of bounds for dimension 1 with size 0

### ISSUE THREAD

**Issue by sherryliu987** [dauparas/LigandMPNN#18]
Getting an error for LigandMPNN

Traceback (most recent call last):
  File "/home/ubuntu/LigandMPNN/run.py", line 794, in <module>
    main(args)
  File "/home/ubuntu/LigandMPNN/run.py", line 353, in main
    feature_dict = featurize(
                   ^^^^^^^^^^
  File "/home/ubuntu/LigandMPNN/data_utils.py", line 945, in featurize
    Y, Y_t, Y_m, D_XY = get_nearest_neighbours(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/LigandMPNN/data_utils.py", line 897, in get_nearest_neighbours
    D_AB_closest = torch.sqrt(L2_AB_nn[:, 0])
                              ~~~~~~~~^^^^^^
IndexError: index 0 is out of bounds for dimension 1 with size 0

**Comment by sherryliu987** [comment]
Am now getting a slightly different error, still out of bounds. My protein only has 193 residues but it seems to be accessing 195? I have not specified any fixed or designed residues. 

  File "/home/ubuntu/LigandMPNN/data_utils.py", line 509, in get_aligned_coordinates
    atom_coords_[CA_dict[code], :] = atom_coords[i]
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
IndexError: index 195 is out of bounds for axis 0 with size 193

**Comment by dauparas** [comment]
Any chance you could share the input PDB so that I can try to replicate this error, please?

**Comment by kimdn** [comment]
I had the similar error
```

==> peptide_design_7513421.err <==
Traceback (most recent call last):
  File "/people/kimd999/script/python/design/LigandMPNN/run.py", line 988, in <module>
    main(args)
  File "/people/kimd999/script/python/design/LigandMPNN/run.py", line 393, in main
    feature_dict = featurize(
                   ^^^^^^^^^^
  File "/qfs/people/kimd999/script/python/design/LigandMPNN/data_utils.py", line 946, in featurize
    Y, Y_t, Y_m, D_XY = get_nearest_neighbours(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/qfs/people/kimd999/script/python/design/LigandMPNN/data_utils.py", line 898, in get_nearest_neighbours
    D_AB_closest = torch.sqrt(L2_AB_nn[:, 0])
                              ~~~~~~~~^^^^^^
IndexError: index 0 is out of bounds for dimension 1 with size 0
```

This error occurred when there is no element notation at end of each line like

```
ATOM     39  C   GLY A  10     -12.985 -10.409 -16.815  1.00  0.00
ATOM     40  O   GLY A  10     -13.118 -11.007 -15.747  1.00  0.00
HETATM   41  N   LIG    11     -38.288  36.148   5.348  1.00  1.00
HETATM   42  CA  LIG    11     -37.548  34.892   5.336  1.00  1.00
```

Adding element like
```

ATOM     39  C   GLY A  10     -12.985 -10.409 -16.815  1.00  0.00           C
ATOM     40  O   GLY A  10     -13.118 -11.007 -15.747  1.00  0.00           O
HETATM   41  N   LIG    11     -38.288  36.148   5.348  1.00  1.00           N
HETATM   42  CA  LIG    11     -37.548  34.892   5.336  1.00  1.00           C
HETATM   43  C   LIG    11     -36.391  34.925   6.329  1.00  1.00           C

```
solved

**Comment by youarebitchright** [comment]
`Traceback (most recent call last):
  File "/home/hk/LigandMPNN/run.py", line 990, in <module>
    main(args)
  File "/home/hk/LigandMPNN/run.py", line 395, in main
    feature_dict = featurize(
                   ^^^^^^^^^^
  File "/home/hk/LigandMPNN/data_utils.py", line 946, in featurize
    Y, Y_t, Y_m, D_XY = get_nearest_neighbours(
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hk/LigandMPNN/data_utils.py", line 898, in get_nearest_neighbours
    D_AB_closest = torch.sqrt(L2_AB_nn[:, 0])
                              ~~~~~~~~^^^^^^
IndexError: index 0 is out of bounds for dimension 1 with size 0
`
I still have this problem. When I use a small ligand, there's no problem. Like:
`1    HETATM    1  S   UNK     0       1.951  -5.706  -9.606  0.00  0.00          S
   1 HETATM    2  O   UNK     0       2.219  -5.623  -8.128  0.00  0.00          O
   2 HETATM    3  C   UNK     0       1.506  -4.040 -10.160  0.00  0.00          C
   3 HETATM    4  C   UNK     0       2.015  -2.987  -9.193  0.00  0.00          C
   4 HETATM    5  O   UNK     0       3.411  -3.161  -8.991  0.00  0.00          O
   5 HETATM    6  H   UNK     0       3.522  -3.942  -8.420  0.00  0.00          H
   6 HETATM    7  C   UNK     0       3.548  -5.805 -10.414  0.00  0.00          C
   7 HETATM    8  C   UNK     0       3.856  -4.933 -11.459  0.00  0.00          C
   8 HETATM    9  C   UNK     0       5.099  -5.010 -12.087  0.00  0.00          C
   9 HETATM   10  C   UNK     0       6.034  -5.957 -11.672  0.00  0.00          C
  10 HETATM   11  C   UNK     0       5.725  -6.829 -10.627  0.00  0.00          C
  11 HETATM   12  C   UNK     0       4.482  -6.752  -9.998  0.00  0.00          C
  12 ATOM     13  N   MET A   1      28.203  -1.485   4.851  1.00 46.20           N
  13 ATOM     14  CA  MET A   1      27.274  -0.580   4.143  1.00 57.23           C
`
But when I use a big ligand, the error comes up.
`  1 HETATM    1  S   UNK     0       0.196  -1.579  -9.144  0.00  0.00          S
   1 HETATM    2  O   UNK     0      -0.258  -2.056  -7.793  0.00  0.00          O
   2 HETATM    3  C   UNK     0       1.344  -2.815  -9.763  0.00  0.00          C
   3 HETATM    4  C   UNK     0       1.868  -3.764  -8.883  0.00  0.00          C
   4 HETATM    5  C   UNK     0       2.755  -4.698  -9.419  0.00  0.00          C
   5 HETATM    6  N   UNK     0       3.442  -5.746  -8.860  0.00  0.00          N
   6 HETATM    7  C   UNK     0       3.126  -4.716 -10.760  0.00  0.00          C
   7 HETATM    8  C   UNK     0       4.176  -6.337  -9.850  0.00  0.00          C
   8 HETATM    9  H   UNK     0       3.410  -6.031  -7.891  0.00  0.00          H
   9 HETATM   10  N   UNK     0       4.011  -5.741 -11.009  0.00  0.00          N
  10 HETATM   11  HN  UNK     0       4.443  -5.985 -11.900  1.00  0.00          H
  11 HETATM   12  C   UNK     0       2.592  -3.753 -11.632  0.00  0.00          C
  12 HETATM   13  C   UNK     0       1.699  -2.806 -11.115  0.00  0.00          C
  13 HETATM   14  N   UNK     0       4.966  -7.423  -9.572  0.00  0.00          N
  14 HETATM   15  C   UNK     0       6.334  -7.428  -9.300  0.00  0.00          C
  15 HETATM   16  O   UNK     0       7.088  -6.463  -9.259  0.00  0.00          O
  16 HETATM   17  H   UNK     0       4.499  -8.327  -9.563  0.00  0.00          H
10 HETATM   19  C   UNK     0       6.362  -9.681 -10.059  0.00  0.00          C
   9 HETATM   20  C   UNK     0       1.403  -0.257  -8.865  0.00  0.00          C
   8 HETATM   21  C   UNK     0       0.812   0.832  -7.982  0.00  0.00          C
   7 HETATM   22  C   UNK     0      -0.704   0.874  -8.096  0.00  0.00          C
   6 ATOM     23  N   MET A   1      28.203  -1.485   4.851  1.00 46.20           N
   5 ATOM     24  CA  MET A   1      27.274  -0.580   4.143  1.00 57.23           C
`
