### ISSUE TITLE
Can I run LigandMPNN on my Windows Laptop?

### ISSUE THREAD

**Issue by emilyrkang** [dauparas/LigandMPNN#20]
I followed the installation instructions but when I try to run:

 py run.py --seed 111 --pdb_path "./inputs/1BC8.pdb" --out_folder "./outputs/default"

I get the following error message: 

PS C:\LigandMPNN> py run.py --seed 111 --pdb_path "./inputs/1BC8.pdb" --out_folder "./outputs/default"
Traceback (most recent call last):
  File "C:\LigandMPNN\run.py", line 24, in <module>
    from sc_utils import Packer, pack_side_chains
  File "C:\LigandMPNN\sc_utils.py", line 17, in <module>
    from openfold.data.data_transforms import atom37_to_torsion_angles, make_atom14_masks
  File "C:\LigandMPNN\openfold\data\data_transforms.py", line 24, in <module>
    from openfold.np import residue_constants as rc
  File "C:\LigandMPNN\openfold\np\__init__.py", line 11, in <module>
    _modules = [(m, importlib.import_module("." + m, __name__)) for m in __all__]
  File "C:\LigandMPNN\openfold\np\__init__.py", line 11, in <listcomp>
    _modules = [(m, importlib.import_module("." + m, __name__)) for m in __all__]
  File "C:\Users\EmilyRobertsKang\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\LigandMPNN\openfold\np\protein.py", line 23, in <module>
    from openfold.np import residue_constants
  File "C:\LigandMPNN\openfold\np\residue_constants.py", line 24, in <module>
    import tree
ModuleNotFoundError: No module named 'tree'

No version of pip installing tree seems to work. Openfold only has installation instructions for Linux, does this mean I can't run Openfold and/or LigandMPNN on my Windows Laptop (Windows 11 Pro operating system)?

**Comment by YaoYinYing** [comment]
> does this mean I can't run Openfold and/or LigandMPNN on my Windows Laptop

LigandMPNN works well on Windows, OpenFold does not.🙃 https://github.com/dauparas/LigandMPNN/pull/16

**Comment by dauparas** [comment]
Try using the requirements.txt file to make conda env
