### ISSUE TITLE
Problem with Ligand

### ISSUE THREAD

**Issue by jmProteins2024** [dauparas/LigandMPNN#23]
We have a pdb file with the La metal as a ligand

![image](https://github.com/dauparas/LigandMPNN/assets/166163441/8dc75c05-8606-4475-bb34-d75fc34eaabb)

and when we run we get this error:

![image](https://github.com/dauparas/LigandMPNN/assets/166163441/990fd7e7-f496-4d63-a293-430b8a90f5a8)

This is the code we are running is

python run.py \
        --model_type "ligand_mpnn" \
        --seed 111 \
        --pdb_path "./inputs/test.pdb" \
        --out_folder "./outputs/test" \
        --pack_side_chains 1 \
        --number_of_packs_per_design 4 \
        --pack_with_ligand_context 1 \
        --fixed_residues "A3" \
        --repack_everything 1

Do you know what we could be doing wrong?

**Comment by dauparas** [comment]
Could you share the input PDB so that I can try to replicate this error, please? Feel free to set all coordinates to random numbers if it is a confidential structure.

**Comment by Arindam337** [comment]
I have a protein that has an open conformation and upon ligand binding it takes a closed conformation. When I give closed conformation without ligand as input to the LigandMPNN, it works and gives an output. However, if I use open conformation as input, it is showing an error - 
ValueError: shape mismatch: value array of shape (1,1104) could not be broadcast to indexing result of shape (1103,).

**Comment by KeaunAmani** [comment]
@Arindam337 The issue is likely occurring because there is a gap somewhere in your structure. I'm also experiencing the same issue when I run structures with missing residues / gaps

@dauparas Would it be possible to extend LigandMPNN support to work with such structures? I'm sure it would be a greatly appreciated feature for many of us.

**Comment by kimdn** [comment]
> I have a protein that has an open conformation and upon ligand binding it takes a closed conformation. When I give closed conformation without ligand as input to the LigandMPNN, it works and gives an output. However, if I use open conformation as input, it is showing an error - ValueError: shape mismatch: value array of shape (1,1104) could not be broadcast to indexing result of shape (1103,).

I have a similar error

`  File "/people/kimd999/bin/Miniconda3-py311_24.5.0-0-Linux-x86_64/envs/ligandmpnn_env/lib/python3.11/site-packages/prody/atomic/subset.py", line 199, in setData
    array[self._indices] = value
    ~~~~~^^^^^^^^^^^^^^^
ValueError: shape mismatch: value array of shape (1,2448) could not be broadcast to indexing result of shape (2446,)`

**Comment by chelseashuu** [comment]
@kimdn Hello! I am getting the same error 
Traceback (most recent call last):
  File "/gpfs/fs001/cbica/home/shuch/software/LigandMPNN/run.py", line 990, in <module>
    main(args)
  File "/gpfs/fs001/cbica/home/shuch/software/LigandMPNN/run.py", line 587, in main
    backbone.setResnames(seq_prody)
  File "/cbica/home/shuch/.local/lib/python3.11/site-packages/prody/atomic/fields.py", line 276, in setMethod
    return fn(self, data)
           ^^^^^^^^^^^^^^
  File "/cbica/home/shuch/.local/lib/python3.11/site-packages/prody/atomic/subset.py", line 199, in setData
    array[self._indices] = value
    ~~~~~^^^^^^^^^^^^^^^
ValueError: shape mismatch: value array of shape (1,636) could not be broadcast to indexing result of shape (159,)

but I have removed all the TER residues. My ligand is detected. I'm not sure why the 636 is appearing as a multiple of 159 (# of residues I have) 

<img width="597" alt="Image" src="https://github.com/user-attachments/assets/7ed0d50b-6c23-44c0-bb2a-01437e8a9ed0" />

**Comment by SMG-fly** [comment]
Hello!

I also ran into this Error and found a solution that has been working well for me.

I think the exact cause is how the script handles backbone atom counts. The issue seems to occur when an input PDB file contains a residue where not all four backbone atoms (N, CA, C, O) are present. For example, a residue might only have 3 of its backbone atoms in the file.
```
ATOM   1958  CZ  PHE A 256      -7.670 -62.839  -6.214  1.00 21.97           C  
ATOM   1959  N   ALA A 257     -11.519 -67.883  -2.910  1.00 26.55           N  
ATOM   1960  CA  ALA A 257     -12.608 -68.519  -2.181  1.00 29.69           C  
ATOM   1961  C   ALA A 257     -12.840 -67.831  -0.836  1.00 33.42           C  
ATOM   1962  CB  ALA A 257     -12.320 -70.006  -1.981  1.00 29.68           C  
ATOM   1963  N   ASP A 258     -14.083 -67.893  -0.363  1.00 37.75           N  
```
The [original code](https://github.com/dauparas/LigandMPNN/blob/26ec57ac976ade5379920dbd43c7f97a91cf82de/run.py#L581-L586) assumes every residue has 4 backbone atoms (N, CA, C, O). This causes a size mismatch error for PDBs with incomplete residues.
```
seq_prody = np.array([restype_1to3[AA] for AA in list(seq)])[None, ].repeat(4, 1)
bfactor_prody = (loss_per_residue_stack[ix].cpu().numpy()[None, :].repeat(4, 1))

```
Here’s the code I'm using:
```
correct_resnames = []
correct_bfactors = []

# This counter will only advance for residues that have a CA atom.
seq_idx = 0

for residue in backbone.getHierView().iterResidues():
    num_atoms_in_residue = residue.numAtoms()

    # Check if the residue has an Alpha Carbon (CA), which is the criterion used to build `protein_dict`.
    # since sequence was created based on protein_dict["S"]
    if residue.select('name CA') is not None:
        new_resname = restype_1to3[seq[seq_idx]]
        residue_bfactor = loss_per_residue_stack[ix, seq_idx].item()
        seq_idx += 1
    else:
        # This residue was filtered out (no CA).
        # Keep its original name to maintain the structure's integrity.
        new_resname = residue.getResname()
        residue_bfactor = 0.0

    correct_resnames.extend([new_resname] * num_atoms_in_residue)
    correct_bfactors.extend([residue_bfactor] * num_atoms_in_residue)

seq_prody = np.array(correct_resnames)
bfactor_prody = np.array(correct_bfactors)
```
This ensures the array sizes always match the actual number of backbone atoms. 
Hope this is helpful for anyone else running into this!
