### ISSUE TITLE
2 design a new sequence and pack side chains (return 4 side chain packing samples)

### ISSUE THREAD

**Issue by amelie-iska** [dauparas/LigandMPNN#24]
Running the following command:
```bash
python run.py \
        --model_type "ligand_mpnn" \
        --seed 111 \
        --pdb_path "./inputs/1BC8.pdb" \
        --out_folder "./outputs/sc_default" \
        --pack_side_chains 1 \
        --number_of_packs_per_design 4 \
        --pack_with_ligand_context 1
```
returns the following error:
```bash
Packing side chains...
Traceback (most recent call last):
  File "/home/workspace/proteins/LigandMPNN/run.py", line 981, in <module>
    main(args)
  File "/home/workspace/proteins/LigandMPNN/run.py", line 517, in main
    sc_dict = pack_side_chains(
              ^^^^^^^^^^^^^^^^^
  File "/home/workspace/proteins/LigandMPNN/sc_utils.py", line 67, in pack_side_chains
    torsion_dict = make_torsion_features(feature_dict, repack_everything)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/workspace/proteins/LigandMPNN/sc_utils.py", line 212, in make_torsion_features
    xyz14_noised = feats.frames_and_literature_positions_to_atom14_pos(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/workspace/proteins/LigandMPNN/openfold/utils/feats.py", line 253, in frames_and_literature_positions_to_atom14_pos
    group_mask = nn.functional.one_hot(
                 ^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: one_hot is only applicable to index tensor.
```

**Comment by dauparas** [comment]
I am not getting this error running in the environment specified by requirements.txt ; I added .long() https://github.com/dauparas/LigandMPNN/commit/091ab1ff5fb4d13854cf6a7c41ec531e1d9d3e67 which might solve your problem.

**Comment by DazLe-Q** [comment]
> I am not getting this error running in the environment specified by requirements.txt ; I added .long() [091ab1f](https://github.com/dauparas/LigandMPNN/commit/091ab1ff5fb4d13854cf6a7c41ec531e1d9d3e67) which might solve your problem.

Hi, I am currently facing the same issue. Because of some problems with the compatibility of dependencies with my machine, I've commented out all the lines in requirements.txt that start with 'nvidia-' along with 'triton' to install (follow this instruction https://github.com/dauparas/LigandMPNN/issues/58#issuecomment-3192848892). Does these changes affect the program?
