### ISSUE TITLE
Design a new sequence and pack side chains with RFNA Output

### ISSUE THREAD

**Issue by Leo-T-Zang** [dauparas/LigandMPNN#34]
Hi @dauparas ,

Thanks for the work!

I am trying to design new sequence of protein-DNA complex that folded by RFNA model. Yet I met following error:

```
Traceback (most recent call last):
  File "/workspace/work/LigandMPNN/run.py", line 991, in <module>
    main(args)
  File "/workspace/work/LigandMPNN/run.py", line 396, in main
    feature_dict = featurize(
  File "/workspace/work/LigandMPNN/data_utils.py", line 946, in featurize
    Y, Y_t, Y_m, D_XY = get_nearest_neighbours(
  File "/workspace/work/LigandMPNN/data_utils.py", line 898, in get_nearest_neighbours
    D_AB_closest = torch.sqrt(L2_AB_nn[:, 0])
IndexError: index 0 is out of bounds for dimension 1 with size 0
```
The command I called is:

```
python run.py \
        --model_type "ligand_mpnn" \
        --seed 111 \
        --pdb_path "example.pdb" \
        --out_folder "./example" \
        --pack_side_chains 1 \
        --number_of_packs_per_design 0 \
        --temperature 0.1 \
        --pack_with_ligand_context 1
```
example.pdb file can be found in this link (https://drive.google.com/file/d/16rRDi5sVqTONDIU5h7hpqBBWco6hb_uf/view?usp=sharing).

Can you please help me out?

Thanks a lot!

**Comment by Leo-T-Zang** [comment]
Seems like the problem can be solved by adding Element symbol manually to DNA motifs.
